"""Generated operation table. DO NOT EDIT: run scripts/sync_sdk_contract.py."""

OPENAPI_VERSION = '1.0.0'

OPERATIONS = (
    {"method": 'GET', "path": '/metrics', "operation_id": 'getMetrics'},
    {"method": 'GET', "path": '/v1/connections', "operation_id": 'listConnections'},
    {"method": 'DELETE', "path": '/v1/connections/{id}', "operation_id": 'killConnection'},
    {"method": 'GET', "path": '/v1/connections/{id}', "operation_id": 'getConnection'},
    {"method": 'GET', "path": '/v1/datagram-associations', "operation_id": 'listDatagramAssociations'},
    {"method": 'DELETE', "path": '/v1/datagram-associations/{id}', "operation_id": 'killDatagramAssociation'},
    {"method": 'GET', "path": '/v1/datagram-associations/{id}', "operation_id": 'getDatagramAssociation'},
    {"method": 'GET', "path": '/v1/datagram-proxies', "operation_id": 'listDatagramProxies'},
    {"method": 'POST', "path": '/v1/datagram-proxies', "operation_id": 'createDatagramProxy'},
    {"method": 'DELETE', "path": '/v1/datagram-proxies/{name}', "operation_id": 'deleteDatagramProxy'},
    {"method": 'GET', "path": '/v1/datagram-proxies/{name}', "operation_id": 'getDatagramProxy'},
    {"method": 'PATCH', "path": '/v1/datagram-proxies/{name}', "operation_id": 'patchDatagramProxy'},
    {"method": 'GET', "path": '/v1/datagram-proxies/{name}/faults', "operation_id": 'listDatagramFaults'},
    {"method": 'POST', "path": '/v1/datagram-proxies/{name}/faults', "operation_id": 'addDatagramFault'},
    {"method": 'DELETE', "path": '/v1/datagram-proxies/{name}/faults/{id}', "operation_id": 'deleteDatagramFault'},
    {"method": 'GET', "path": '/v1/datagram-proxies/{name}/faults/{id}', "operation_id": 'getDatagramFault'},
    {"method": 'PATCH', "path": '/v1/datagram-proxies/{name}/faults/{id}', "operation_id": 'patchDatagramFault'},
    {"method": 'GET', "path": '/v1/health', "operation_id": 'getHealth'},
    {"method": 'GET', "path": '/v1/history', "operation_id": 'getHistory'},
    {"method": 'GET', "path": '/v1/proxies', "operation_id": 'listProxies'},
    {"method": 'POST', "path": '/v1/proxies', "operation_id": 'createProxy'},
    {"method": 'DELETE', "path": '/v1/proxies/{name}', "operation_id": 'deleteProxy'},
    {"method": 'GET', "path": '/v1/proxies/{name}', "operation_id": 'getProxy'},
    {"method": 'PATCH', "path": '/v1/proxies/{name}', "operation_id": 'patchProxy'},
    {"method": 'GET', "path": '/v1/proxies/{name}/faults', "operation_id": 'listFaults'},
    {"method": 'POST', "path": '/v1/proxies/{name}/faults', "operation_id": 'addFault'},
    {"method": 'DELETE', "path": '/v1/proxies/{name}/faults/{id}', "operation_id": 'deleteFault'},
    {"method": 'GET', "path": '/v1/proxies/{name}/faults/{id}', "operation_id": 'getFault'},
    {"method": 'PATCH', "path": '/v1/proxies/{name}/faults/{id}', "operation_id": 'patchFault'},
    {"method": 'POST', "path": '/v1/reset', "operation_id": 'resetService'},
    {"method": 'POST', "path": '/v1/scenarios/apply', "operation_id": 'applyScenario'},
    {"method": 'POST', "path": '/v1/scenarios/compile', "operation_id": 'compileSchedule'},
    {"method": 'POST', "path": '/v1/scenarios/validate', "operation_id": 'validateSchedule'},
    {"method": 'DELETE', "path": '/v1/scenarios/{id}', "operation_id": 'cancelScenario'},
    {"method": 'GET', "path": '/v1/scenarios/{id}', "operation_id": 'getScenario'},
    {"method": 'GET', "path": '/v1/version', "operation_id": 'getVersion'},
)

STREAM_FAULT_TAGS = ('bandwidth', 'blackhole', 'disconnect', 'latency', 'limit-data', 'slice', 'slow-close', 'stream-loss')

DATAGRAM_FAULT_TAGS = ('bandwidth', 'delay', 'duplicate', 'loss', 'payload-corrupt', 'reorder')

SCENARIO_ACTION_TAGS = ('remove-datagram-fault', 'remove-fault', 'set-datagram-plan', 'set-plan')

OPERATION_METHODS = {
    'addDatagramFault': 'add_datagram_fault',
    'addFault': 'add_fault',
    'applyScenario': 'apply_scenario',
    'cancelScenario': 'cancel_scenario',
    'compileSchedule': 'compile_schedule',
    'createDatagramProxy': 'create_datagram_proxy',
    'createProxy': 'create_proxy',
    'deleteDatagramFault': 'delete_datagram_fault',
    'deleteDatagramProxy': 'delete_datagram_proxy',
    'deleteFault': 'delete_fault',
    'deleteProxy': 'delete_proxy',
    'getConnection': 'get_connection',
    'getDatagramAssociation': 'get_datagram_association',
    'getDatagramFault': 'get_datagram_fault',
    'getDatagramProxy': 'get_datagram_proxy',
    'getFault': 'get_fault',
    'getHealth': 'health',
    'getHistory': 'history',
    'getMetrics': 'metrics_text',
    'getProxy': 'get_proxy',
    'getScenario': 'get_scenario',
    'getVersion': 'version',
    'killConnection': 'kill_connection',
    'killDatagramAssociation': 'kill_datagram_association',
    'listConnections': 'list_connections',
    'listDatagramAssociations': 'list_datagram_associations',
    'listDatagramFaults': 'list_datagram_faults',
    'listDatagramProxies': 'list_datagram_proxies',
    'listFaults': 'list_faults',
    'listProxies': 'list_proxies',
    'patchDatagramFault': 'patch_datagram_fault',
    'patchDatagramProxy': 'patch_datagram_proxy',
    'patchFault': 'patch_fault',
    'patchProxy': 'patch_proxy',
    'resetService': 'reset',
    'validateSchedule': 'validate_schedule',
}
