[package]
name = "eggchaos-eggfetch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Eggfetch Dialer integration for eggchaos"

[features]
default = []
http2 = ["eggfetch-core/http2"]

[dependencies]
eggchaos-core = { path = "../eggchaos-core", version = "0.1.0" }
eggfetch-core.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
bytes.workspace = true
eggchaos-experiment = { path = "../eggchaos-experiment", version = "0.1.0" }
h2.workspace = true
http.workspace = true
rcgen.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
